import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DefaultLayout } from "@/components/default-layout";
import { PropsWithChildren } from "react";
import { TRPCProvider } from "@/components/trpc-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default ({
  children,
}: PropsWithChildren) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TRPCProvider>
          <DefaultLayout>
            {children}
          </DefaultLayout>
        </TRPCProvider>
      </body>
    </html>
  );
}
